### ISSUE TITLE
Refactor generateRandomNumbers() method

### ISSUE THREAD

**Issue by kulcsarrudolf** [Kulcsarzsolt/take6#2]
https://stackoverflow.com/questions/8115722/generating-unique-random-numbers-in-java

**Comment by Kulcsarzsolt** [comment]
https://gist.github.com/Kulcsarzsolt/4b2ed478dbc909f36feb74ac924ea21b

**Comment by Kulcsarzsolt** [comment]
This method is removed since it not used.
